version: '2'

services:
  web:
    build: .
    ports:
      - "5000:3000"
    depends_on:
      - 'database'
    volumes:
      - .:/usr/src/cenzo-city
    env_file:
      - .env/development/database
      - .env/development/web

  database:
      image: postgres
      env_file:
        - .env/development/database
      volumes:
        - db-data:/var/lib/postgresql/data


volumes:
  db-data:
